### PR TITLE
Add a slot with an uninitialized token by calling C_GetSlotList with NULL_PTR

### PR DESCRIPTION
**Pull request by bellgrim**
Calling C_GetSlotList with NULL_PTR will now make sure that there is always a slot with an uninitialized token.

### CODE REVIEW

**Comment by larssilven** [comment]
I think that you also should remove the creation of an empty slot after C_Initialize since it is not needed any more with you solution:
diff --git a/src/lib/slot_mgr/SlotManager.cpp b/src/lib/slot_mgr/SlotManager.cpp
index c63a759..8176a72 100644
--- a/src/lib/slot_mgr/SlotManager.cpp
+++ b/src/lib/slot_mgr/SlotManager.cpp
@@ -46,9 +46,6 @@ SlotManager::SlotManager(ObjectStore* objectStore)
                Slot* newSlot = new Slot(objectStore, i, objectStore->getToken(i));
                slots.push_back(newSlot);
        }
-
-       // Add an empty slot
-       slots.push_back(new Slot(objectStore, objectStore->getTokenCount()));
 }
 
 // Destructor

**Comment by bellgrim** [comment]
You are not required to call C_GetSlotList before e.g. calling C_OpenSession. So it is good to have that initial slot added. One example is when working with command line utilities. The first command could be to display available slots (C_GetSlotList/C_GetSlotInfo/C_GetTokenInfo) then the next one could be used to interact with a given slot (C_OpenSession/C_Login/...). The empty uninitialized token is not persistent between the two different command calls, so we always need to make sure that there is one token available.

**Comment by larssilven** [comment]
I see what you mean. Not a good idea to have an application that is depending on that there is an existing token on a certain slot ID. Slot IDs should always be fetched with the C_GetSlotList in the application before using them since p11 will not guarantee that you get same IDs when a new application is started. But there are applications that relies on that slot IDs are as before after application start and it is good if these apps also could use this p11. I'm actually looking on another change that will make the slot ID of an existing token the same even after a new token has been added.

So I'm totally satisfied with this. Thank you very much.

**Comment by bellgrim** [comment]
Applications like OpenDNSSEC will use the token label to find the correct token. But simple tools like softhsm2-util use the slot number. There is a discussion in #143 to change this.

**Comment by larssilven** [comment]
The sunpkcs11 wrapper for java used to access a p11 token as a java keystore is not capable of using the token label either. The token is referenced either with slot ID or index in slot list,

**Comment by bellgrim** [comment]
#build

**Comment by bellgrim** [comment]
#build again. Is the disc full on Ubuntu14?

**Comment by bellgrim** [comment]
#build again. The are now more space available on ubuntu14.

**Pull request merged**
