### PR TITLE
Replace PKCS11 headers with a version from p11-kit

### PR DESCRIPTION
**Pull request by abbra**
Since headers provided by OASIS PKCS11 TC have not-exactly free license (they do not allow modification), use an alternative header from p11-kit which is licensed under a more liberal license.

For the context, please look at the discussion on the Fedora Project's legal mailing list: https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/ODP2HLWAZETWVMSAOWMUBGZZXSKLLZ74/

I've asked OASIS PKCS11 TC chair to help with updating licensing terms for the PKCS11 headers they produce but was advised to follow this way as it will take a lot of time to sort things out in the technical committee.

@nmav, I had to expand a bit pkcs11.h from p11-kit to include newer ciphers supported by SoftHSM. I'll submit pkcs11.h back to p11-kit with these updates soon but I'd appreciate if you'd review these changes too.

### CODE REVIEW

**Comment by nmav** [comment]
Looks good to me overall, though I haven't been able to isolate which parts were new. I could review that part when sent to p11-kit.

**Comment by abbra** [comment]
@nmav I submitted https://github.com/p11-glue/p11-kit/pull/181 to have headers updated.

**Comment by abbra** [comment]
Patch updated according to the discussion.

**Comment by abbra** [comment]
@bellgrim this is the final version, merged to p11-kit already.

**Comment by bellgrim** [comment]
Thanks!

**Pull request merged**
