### PR TITLE
implement wrapping and unwrapping of Edwards curve-based private keys

### PR DESCRIPTION
**Pull request by keldonin**
This PR is to support wrapping and unwrapping of Edwards curve-based private keys.  Kindly consider and merge. Let me know if anything is missing.

### CODE REVIEW

**Comment by rijswijk** [comment]
Thanks for the PR, looks like we had all the plumbing already in place to support this. Would you mind adding appropriate unit test cases as well, just to make sure this code gets exercised in the tests? Thanks!

**Comment by keldonin** [comment]
Hi @rijswijk, test cases included in a37c9b80ca2dfae81999651271c694d7ce0757ab.

**Comment by rijswijk** [comment]
Thanks! I think the code looks good, asking @halderen for a review and then to merge to develop.

**Comment by keldonin** [comment]
@halderen, have you had any chance to review this yet?

Thanks!

**Comment by halderen** [comment]
Reviewed, I've not  tested in detail, but everything looks good and will not impact any existing stuff and the unit test looks trustworthy.

**Pull request merged**
