### PR TITLE
Only install softhsm2-dump-db manpage if executable is installed

### PR DESCRIPTION
**Pull request by l1k**
Only install softhsm2-dump-db manpage if executable is installed

### CODE REVIEW

**Comment by jschlyter** [comment]
Looks ok to me. @bellgrim ?

**Comment by bellgrim** [comment]
We do need the man in the dist. I would like it to be something like this:

```diff
diff --git a/src/bin/dump/Makefile.am b/src/bin/dump/Makefile.am
index 1306d84..862321f 100644
--- a/src/bin/dump/Makefile.am
+++ b/src/bin/dump/Makefile.am
@@ -5,11 +5,12 @@ AM_CPPFLAGS =                 -I$(srcdir)/../../lib/cryptoki_compat \
                        -I$(srcdir)/../../lib \
                        @SQLITE3_INCLUDES@
 
-dist_man_MANS =                softhsm2-dump-file.1 softhsm2-dump-db.1
+dist_man_MANS =                softhsm2-dump-file.1
 
 bin_PROGRAMS =         softhsm2-dump-file
 
 if BUILD_OBJECTSTORE_BACKEND_DB
+man_MANS =             softhsm2-dump-db.1
 bin_PROGRAMS +=                softhsm2-dump-db
 endif
 
@@ -19,4 +20,5 @@ softhsm2_dump_db_SOURCES = softhsm2-dump-db.cpp
 
 softhsm2_dump_db_LDADD = @SQLITE3_LIBS@ @YIELD_LIB@
 
-EXTRA_DIST =           $(srcdir)/*.h
+EXTRA_DIST =           $(srcdir)/*.h \
+                       $(srcdir)/softhsm2-dump-db.1
```

Please update the pull request.

**Comment by l1k** [comment]
@bellgrim: You're right. Commit modified as requested and force-pushed. Thanks.

**Comment by bellgrim** [comment]
Thanks, this is looking ok.

Jakob, please merge this pull request.

**Pull request merged**
