### PR TITLE
Issue #190: Support for OpenSSL 1.1.0

### PR DESCRIPTION
**Pull request by bellgrim**

### CODE REVIEW

**Comment by bellgrim** [comment]
#build

**Comment by jariq** [comment]
@bellgrim I am testing this patch on Windows and would like to add some changes (mostly related to win32 build process). However I am not sure whether to open PR against `bellgrim:issue190` branch or wait until this gets merged into `opendnssec:develop`. Any suggestions?

**Comment by bellgrim** [comment]
Thanks for patching the Windows build. Forgot to update the Windows configure script and build files.

If it works I could merge the changes into my branch.

**Comment by jariq** [comment]
You have fixed all the issues that bothered me before I even managed to put a PR together :) However I am not sure about the build notes because I was using slightly different command to configure OpenSSL:

`perl Configure VC-WIN32 --prefix=C:\build\bin\openssl-1.1.0a-x86 --openssldir=C:\build\bin\openssl-1.1.0a-x86\ssl no-shared`

Individual options:
- `openssldir` - without this option I had to run command line in administrator mode because by default those files got installed into `Program Files` folder
- `no-shared` - this option actually enables static build

BTW  I am not sure whether `enable-static-engine` option is still valid in 1.1.0. If I remember correctly the build was successful regardless of its presence. I'll try to investigate this a little more.

**Comment by bellgrim** [comment]
Thanks, update the build notes according to your suggestions.

**Pull request merged**
