### PR TITLE
Unbreak negative mechanism lists in slots.mechanisms + testcase

### PR DESCRIPTION
**Pull request by Jakuje**
Previously, when the list for slots.mechanisms was prefixed with
minus sign "-", the first mechanism was skipped as invalid and
therefore the tool was presenting wrong list of algorithms.

This fixes the initial index for selection of first algorithm
and adds unit test for this scenario.

Follow-up to #455, which recently got some more testing identifying this issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1857272

### CODE REVIEW

**Comment by rijswijk** [comment]
Thanks, we'll review this and get back.

**Comment by Jakuje** [comment]
@rijswijk ping. Any update on this?

**Comment by halderen** [comment]
Roland is on vacation, I'll continue on this starting Friday.

**Comment by abbra** [comment]
@halderen any update? I am not sure who is working on it...

**Comment by rijswijk** [comment]
We have serious time restrictions due to local COVID lockdowns; I looked at the code, it looks good to me. Would still prefer it if @halderen also reviews, as he reviewed the original PR that led to the introduction of this feature.

**Comment by abbra** [comment]
Thank you for the update, @rijswijk. The token parsing code looks OK for me too.
@Jakuje could you please rebase as AppVeyor complains about non-mergeable pull request?

**Comment by Jakuje** [comment]
Rebased.

**Pull request merged**
