### PR TITLE
SOFTHSM-111: Include FIPS-NOTES.md in dist.

### PR DESCRIPTION
**Pull request by bellgrim**

### CODE REVIEW

**Comment by bellgrim** [comment]
#build

**Comment by bellgrim** [comment]
An unrelated jerkin build error, try again.

#build

**Comment by bellgrim** [comment]
The disc was full on ubuntu14

#build

**Comment by bellgrim** [comment]
#build

**Comment by jschlyter** [comment]
can I haz #build ?

**Pull request merged**
