### PR TITLE
Fix errors reported by Visual Studio 2015

### PR DESCRIPTION
**Pull request by jariq**
I've been able to build both 32-bit and 64-bit release of SoftHSMv2 in Visual Studio 2015 Community with these simple changes.

### CODE REVIEW

**Comment by rijswijk** [comment]
Looks OK to me, have you checked this builds correctly on other OSes by any chance?

**Comment by jariq** [comment]
It builds correctly on my 64-bit Ubuntu 14.04 with gcc and it seems [Travis CI build](https://travis-ci.org/opendnssec/SoftHSMv2/builds/75765652) is also passing.

**Comment by rijswijk** [comment]
OK, great. I'll leave it to @bellgrim to merge the change, he's back soon.

**Comment by bellgrim** [comment]
#build

**Comment by bellgrim** [comment]
Thank you, merging this patch

**Pull request merged**
