### PR TITLE
some minor changes

### PR DESCRIPTION
**Pull request by agrandville**
thank's to PVS-Studio

### CODE REVIEW

**Comment by bellgrim** [comment]
#build

**Comment by bellgrim** [comment]
Thanks for the patch, it is looking good. Did PVS-Studio find a lot of issues?

**Comment by agrandville** [comment]
You're right ! There is no raison to round up the maxSize if ciphered data length is smaller than the key, no output will be produced.

regarding the crash,I cleanup the code and confirm a crash in C_EncryptUpdate.

```cpp
...
CK_ULONG ulCipherTextMultiLen1 = 0;
CK_ULONG ulCipherTextMultiLen2 = 0;
CK_ULONG ulCipherTextMultiLen3 = 0;
rv = C_EncryptInit(hSession, &mechanism, hKey);
CPPUNIT_ASSERT(rv == CKR_OK);
ulCipherTextMultiLen1 = sizeof(cipherTextMulti);
rv = C_EncryptUpdate(hSession, plainText, 4, cipherTextMulti, &ulCipherTextMultiLen1);
....
````

exception

my callstack
```
 	msvcp120d.dll!std::_Debug_message(const wchar_t * message, const wchar_t * file, unsigned int line) Line 15	C++
>	p11test.exe!std::vector<unsigned char,SecureAllocator<unsigned char> >::operator[](unsigned int _Pos) Line 1201	C++
 	p11test.exe!ByteString::byte_str() Line 191	C++
 	p11test.exe!SymEncryptUpdate(Session * session, unsigned char * pData, unsigned long ulDataLen, unsigned char * pEncryptedData, unsigned long * pulEncryptedDataLen) Line 2360	C++
 	p11test.exe!SoftHSM::C_EncryptUpdate(unsigned long hSession, unsigned char * pData, unsigned long ulDataLen, unsigned char * pEncryptedData, unsigned long * pulEncryptedDataLen) Line 2384	C++
 	p11test.exe!C_EncryptUpdate(unsigned long hSession, unsigned char * pData, unsigned long ulDataLen, unsigned char * pEncryptedData, unsigned long * pulEncryptedDataLen) Line 595	C++
 	p11test.exe!SymmetricAlgorithmTests::aesEncryptDecrypt(unsigned long mechanismType, unsigned long hSession, unsigned long hKey) Line 277	C++
```
the respondent
outofbound

app crash while trying to read the first element of an empty array that's why I check the encryptedData length, have a look at the SymEncryptFinal function, a test is present  

````cpp
static CK_RV SymEncryptFinal(Session* session, CK_BYTE_PTR pEncryptedData, CK_ULONG_PTR pulEncryptedDataLen)
{
.../...
	if (!cipher->encryptFinal(encryptedFinal))
	{
		session->resetOp();
		return CKR_GENERAL_ERROR;
	}

	if (encryptedFinal.size() != 0) /// yeahh !!
	{
		memcpy(pEncryptedData, encryptedFinal.byte_str(), encryptedFinal.size());
	}

````
on the other hand, for now, I have no explanation for the success on ubuntu ?!?!
My system : windows 10, Visual Studio 2013, Project settings x86 Debug 

Arnaud

**Comment by agrandville** [comment]
may be an explanation for the difference between the Ubuntu and Windows version
http://www.cplusplus.com/reference/vector/vector/operator%5B%5D/
vector::at is bound-checked not the [] operator who produces undefined results.

**Comment by bellgrim** [comment]
Ok, then we agree that the last commit should be updated to only contain the fix for memcpy and no adjustment on the buffer handling (rounding up).

**Comment by agrandville** [comment]
ok

**Comment by bellgrim** [comment]
Why did you close this issue? The other changes were ok or maybe you are opening a new pull request?

**Pull request closed without merging**
