### PR TITLE
crypto: openssl: libressl support

### PR DESCRIPTION
**Pull request by alonbl**
Hi,

Support libressl with trivial changes, passes all tests.

BTW: Running programs during autoconf is highly discouraged as cross-compile will fail. Please consider to use only the pre-processor in order to detect algorithms and versions.

BTW2: If you run something while allowing to specify --with-xxx=prefix, you should also set LD_PRELOAD.

Thanks!

### CODE REVIEW

**Comment by bellgrim** [comment]
Thanks for adding support for libressl. Will have a look on this within a few weeks.

**Comment by bellgrim** [comment]
#build

**Comment by alonbl** [comment]
#build

**Comment by alonbl** [comment]
@bellgrim: this should be trivial and it did pass the current CI (those that were available anyway).

**Comment by alonbl** [comment]
ping? I would like to avoid patching this every time in gentoo.
Thanks!

**Pull request merged**
