### PR TITLE
Add a configuration option to reset SoftHSM state on fork

### PR DESCRIPTION
**Pull request by ansasaki**
Add the configuration option "library.reset_on_fork".  When set to "true", will
make SoftHSM to reset its state on fork.

---
Was  "Add a configuration option to emulate hardware device"

Previous description:

Add the configuration option "slots.hardware".  When set to "true", will
make SoftHSM to set the CKF_HW_SLOT flag in the structure returned by
C_GetSlotInfo().

The added configuration option is useful for testing applications which
requires hardware slots and/or change behaviour for hardware slots.

Also reset the SoftHSM instance when a fork is detected and the
CKF_HW_SLOT flag is set. This emulates a common behaviour for
hardware devices.

### CODE REVIEW

**Comment by rijswijk** [comment]
Thank you for your PR; I was wondering if you could provide a description of the particular use case for which you implemented this functionality. Also, before merging, you should know that we are working on a project to support "real" hardware features in an upcoming SoftHSM release. One of your Red Hat colleagues (@letoams) is on the SoftHSM governance board and knows more about these plans, I suggest you also reach out to him.

**Comment by ansasaki** [comment]
> Thank you for your PR; I was wondering if you could provide a description of the particular use case for which you implemented this functionality.

We had problems in the past with forking applications which behave well with SoftHSM, but would fail with real smart cards. When the application forks, the SoftHSM duplicates it's whole state, since everything is on memory. That is not the case with real smart cards.

With this feature, we can automate our test suite to try both behaviours and find these "bad" applications which can't handle de-initialization on fork. Without this, tests with real smart cards are required to detect such "bad" applications.

> Also, before merging, you should know that we are working on a project to support "real" hardware features in an upcoming SoftHSM release. One of your Red Hat colleagues (@letoams) is on the SoftHSM governance board and knows more about these plans, I suggest you also reach out to him.

Thank you for letting me know, I'll get in touch with him to know what his project is about. But I feel it is not what I need, but rather the opposite. What I want is to be able to test some hardware behaviour even when I don't have such hardware. I guess his work is about adding support for using hardware to store objects, or to encrypt the objects?

**Comment by rijswijk** [comment]
> > Thank you for your PR; I was wondering if you could provide a description of the particular use case for which you implemented this functionality.
> 
> We had problems in the past with forking applications which behave well with SoftHSM, but would fail with real smart cards. When the application forks, the SoftHSM duplicates it's whole state, since everything is on memory. That is not the case with real smart cards.
> 
> With this feature, we can automate our test suite to try both behaviours and find these "bad" applications which can't handle de-initialization on fork. Without this, tests with real smart cards are required to detect such "bad" applications.

Thanks for explaining the use case, and what an odd behaviour; this almost has to be a deliberate implementation on the part of the smart card PKCS11 implementer, because on a normal fork you'd expect the full state including libraries and their state to be replicated. Maybe it is to do with the PC/SC session becoming invalid after ```fork()```?

> 
> > Also, before merging, you should know that we are working on a project to support "real" hardware features in an upcoming SoftHSM release. One of your Red Hat colleagues (@letoams) is on the SoftHSM governance board and knows more about these plans, I suggest you also reach out to him.
> 
> Thank you for letting me know, I'll get in touch with him to know what his project is about. But I feel it is not what I need, but rather the opposite. What I want is to be able to test some hardware behaviour even when I don't have such hardware. I guess his work is about adding support for using hardware to store objects, or to encrypt the objects?

No, you're right, it's not what you need, but it is a conflicting development, as it will -- at some point -- lead to a "legitimate" reason to use the ```CKF_HW_SLOT``` flag, but with different semantics.

I would like to ask if you would be willing to re-factor the PR to make this a compile-time feature that is turned off by default (e.g. call it ```--enable-softhw-test```). Then, if you are willing to do so, I'd like to bring this to the attention of the SoftHSM board to discuss it. My reasoning for this is that this is a very specific feature that supports a test use case, whereas work is ongoing on a potentially conflicting major feature release. I hope you understand. Please don't start implementing it quite yet if you say yes, because I'd like to run it past the board first to make sure they're "on board" (pun intended).

**Comment by ansasaki** [comment]
> Thanks for explaining the use case, and what an odd behaviour; this almost has to be a deliberate implementation on the part of the smart card PKCS11 implementer, because on a normal fork you'd expect the full state including libraries and their state to be replicated. Maybe it is to do with the PC/SC session becoming invalid after `fork()`?

I think it is deliberate. Could be because of the PC/SC session, or could be that the module uses some process-to-session matching. In any case, this is a common behaviour among modules.

> I would like to ask if you would be willing to re-factor the PR to make this a compile-time feature that is turned off by default (e.g. call it `--enable-softhw-test`). Then, if you are willing to do so, I'd like to bring this to the attention of the SoftHSM board to discuss it. My reasoning for this is that this is a very specific feature that supports a test use case, whereas work is ongoing on a potentially conflicting major feature release. I hope you understand. Please don't start implementing it quite yet if you say yes, because I'd like to run it past the board first to make sure they're "on board" (pun intended).

I understand the reasoning. What if I added an compilation option to add an extra field to the state for extensions like this one? It could be something like `--enable-testing-extensions`. Then add a field, let's say 32 bits long, and use bit masks for different extensions.

Then I could add a configuration option like `extensions.deinit_on_fork` to set the bit for this behaviour. I'm proposing configuration options because I need a run-time switch.

Maybe it would be interesting for the future to have an extra field for SoftHSM extensions like this one.

**Comment by rijswijk** [comment]
> > Thanks for explaining the use case, and what an odd behaviour; this almost has to be a deliberate implementation on the part of the smart card PKCS11 implementer, because on a normal fork you'd expect the full state including libraries and their state to be replicated. Maybe it is to do with the PC/SC session becoming invalid after `fork()`?
> 
> I think it is deliberate. Could be because of the PC/SC session, or could be that the module uses some process-to-session matching. In any case, this is a common behaviour among modules.
> 
> > I would like to ask if you would be willing to re-factor the PR to make this a compile-time feature that is turned off by default (e.g. call it `--enable-softhw-test`). Then, if you are willing to do so, I'd like to bring this to the attention of the SoftHSM board to discuss it. My reasoning for this is that this is a very specific feature that supports a test use case, whereas work is ongoing on a potentially conflicting major feature release. I hope you understand. Please don't start implementing it quite yet if you say yes, because I'd like to run it past the board first to make sure they're "on board" (pun intended).
> 
> I understand the reasoning. What if I added an compilation option to add an extra field to the state for extensions like this one? It could be something like `--enable-testing-extensions`. Then add a field, let's say 32 bits long, and use bit masks for different extensions.
> 
> Then I could add a configuration option like `extensions.deinit_on_fork` to set the bit for this behaviour. I'm proposing configuration options because I need a run-time switch.
> 
> Maybe it would be interesting for the future to have an extra field for SoftHSM extensions like this one.

I think that would be a good approach, I'm going to consult the SoftHSM board and will get back as soon as I hear from them.

**Comment by rijswijk** [comment]
(for reference: have asked the SoftHSM board for feedback latest by Feb 1st)

**Comment by jariq** [comment]
I've seen this behavior with quite a few commercial HSMs and also found it weird at first but then I found out that [PKCS#11 v2.20](https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.20) states in chapter 6.6.1 that child process should not keep the cryptoki nor login state of the parent:

> Consider a UNIX process **P** which becomes a Cryptoki application by calling `C_Initialize`, and then uses the `fork()` system call to create a child process **C**. Since **P** and **C** have separate address spaces (or will when one of them performs a write operation, if the operating system follows the copy-on-write paradigm), they are not part of the same application. Therefore, if **C** needs to use Cryptoki, it needs to perform its own `C_Initialize` call. Furthermore, if **C** needs to be logged into the token(s) that it will access via Cryptoki, it needs to log into them even if **P** already logged in, since **P** and **C** are completely separate applications.

So IMO compliant PKCS#11 implementation should treat forked process as a completely new process (all states need to be discarted).

**Comment by ansasaki** [comment]
> So IMO compliant PKCS#11 implementation should treat forked process as a completely new process (all states need to be discarted).

Thank you for the information! I always thought that this behaviour was something like a de-facto standard adopted by the vendors. But it is stated in the specification.

Should we consider changing the default SoftHSM behaviour?

**Comment by rijswijk** [comment]
Thanks @jariq that is useful input. I read it slightly differently, in that the text in the PKCS11 spec is prescriptive for applications rather than Cryptoki implementers, and that applications should expect the library to require a separate initialisation, but there is no mandated behaviour for token implementations. Admittedly, the text is ambiguous. Going forward I think a good solution would be to make this behaviour configurable, with the default being the current behaviour.

@ansasaki would you be willing to rework your code to do that? I would then also suggest removing the "hardware emulation" behaviour, since that is not really needed anymore (unless I am mistaken).

**Comment by ansasaki** [comment]
> Thanks @jariq that is useful input. I read it slightly differently, in that the text in the PKCS11 spec is prescriptive for applications rather than Cryptoki implementers, and that applications should expect the library to require a separate initialisation, but there is no mandated behaviour for token implementations. Admittedly, the text is ambiguous. Going forward I think a good solution would be to make this behaviour configurable, with the default being the current behaviour.
> 
> @ansasaki would you be willing to rework your code to do that? I would then also suggest removing the "hardware emulation" behaviour, since that is not really needed anymore (unless I am mistaken).

Sure, I can change my PR to that direction, and drop the option to set the slot as a hardware slot. But I still need the run-time switch for that, which means I still need a configuration option and a way to store the option in the state.

Would the solution I described before (adding an extension field to the state) acceptable for this purpose?

**Comment by rijswijk** [comment]
> > Thanks @jariq that is useful input. I read it slightly differently, in that the text in the PKCS11 spec is prescriptive for applications rather than Cryptoki implementers, and that applications should expect the library to require a separate initialisation, but there is no mandated behaviour for token implementations. Admittedly, the text is ambiguous. Going forward I think a good solution would be to make this behaviour configurable, with the default being the current behaviour.
> > @ansasaki would you be willing to rework your code to do that? I would then also suggest removing the "hardware emulation" behaviour, since that is not really needed anymore (unless I am mistaken).
> 
> Sure, I can change my PR to that direction, and drop the option to set the slot as a hardware slot. But I still need the run-time switch for that, which means I still need a configuration option and a way to store the option in the state.
> 
> Would the solution I described before (adding an extension field to the state) acceptable for this purpose?

I don't think it'd have to be an extension state, given @jariq's input this should be a regular feature. I suggest adding a configuration option ```library.reset_on_fork``` which, if set to ```true``` resets all state after a fork. The config option should be optional and the default should be ```false``` to keep the current behaviour as standard (so as not to inadvertently break anything that depends on it). Does that answer your question?

**Comment by letoams** [comment]
On Wed, 22 Jan 2020, Roland van Rijswijk wrote:

> I don't think it'd have to be an extension state, given @jariq's input this should be a regular feature. I suggest adding
> a configuration option library.reset_on_fork which, if set to true resets all state after a fork. The config option
> should be optional and the default should be false to keep the current behaviour as standard (so as not to inadvertently
> break anything that depends on it). Does that answer your question?

If this option is only used for doing testing and shouldn't be set
during production, then the name library.reset_on_fork is not a
very good one. library.testing.reset_on_fork would be better.

For libreswan, all these options are passed to our daemon with an
--impair- prefix, making it very clear you doing something that
is really not standard and impairs your production quality.

Paul

**Comment by ansasaki** [comment]
> I don't think it'd have to be an extension state, given @jariq's input this should be a regular feature. I suggest adding a configuration option `library.reset_on_fork` which, if set to `true` resets all state after a fork. The config option should be optional and the default should be `false` to keep the current behaviour as standard (so as not to inadvertently break anything that depends on it). Does that answer your question?

Yes it does, thank you.

> If this option is only used for doing testing and shouldn't be set during production, then the name library.reset_on_fork is not a very good one. library.testing.reset_on_fork would be better. For libreswan, all these options are passed to our daemon with an --impair- prefix, making it very clear you doing something that is really not standard and impairs your production quality. Paul

For me this is fine too as the purpose I want to use this option is for testing. But I wouldn't say that is not standard as it is a common behaviour among hardware devices. If an application fails when the option is set, it means the application would fail with many (maybe the majority of) hardware devices. 

I will change my PR with the given inputs.

**Comment by rijswijk** [comment]
> > I don't think it'd have to be an extension state, given @jariq's input this should be a regular feature. I suggest adding a configuration option `library.reset_on_fork` which, if set to `true` resets all state after a fork. The config option should be optional and the default should be `false` to keep the current behaviour as standard (so as not to inadvertently break anything that depends on it). Does that answer your question?
> 
> Yes it does, thank you.
> 
> > If this option is only used for doing testing and shouldn't be set during production, then the name library.reset_on_fork is not a very good one. library.testing.reset_on_fork would be better. For libreswan, all these options are passed to our daemon with an --impair- prefix, making it very clear you doing something that is really not standard and impairs your production quality. Paul
> 
> For me this is fine too as the purpose I want to use this option is for testing. But I wouldn't say that is not standard as it is a common behaviour among hardware devices. If an application fails when the option is set, it means the application would fail with many (maybe the majority of) hardware devices.
> 
> I will change my PR with the given inputs.

I would also say it's not just for testing, so go ahead and make it a standard, albeit default "off" option. Thanks again!

**Comment by ansasaki** [comment]
> I would also say it's not just for testing, so go ahead and make it a standard, albeit default "off" option. Thanks again!

Updated with the agreed behaviour.

@rijswijk Could you please check the new version?

**Comment by rijswijk** [comment]
Thanks! I'm going to ask for a review and will then merge the PR.

**Comment by ansasaki** [comment]
I pushed a small code style fix.

> There seems to be a small memory leak associated with the forking itself. Interestingly, there is about 2KB lost at the child process. How and where baffles me as the memory isn't leaked when faking the fork(), nor when using a memory sanitizer.

I tried to find this memory leak by running under valgrind, but I found just a small memory leak of 192 bytes. I'll open a new PR to fix it.

How are you detecting such memory leak?

**Comment by rijswijk** [comment]
Thanks, and also thanks for the separate PR for this leak. 

One final heads up: I see you added a Red Hat copyright statement in the test code for the feature. While that block is license-compatible with the 2-clause BSD license that SoftHSMv2 has, I just want to make sure that you are aware that the SoftHSM project now lives under the Commons Conservancy, and that governance decisions about the project are made by the SoftHSM Governance Board (on which we currently have a Red Hat representative, @letoams).

**Comment by ansasaki** [comment]
> Thanks, and also thanks for the separate PR for this leak.
> 
> One final heads up: I see you added a Red Hat copyright statement in the test code for the feature. While that block is license-compatible with the 2-clause BSD license that SoftHSMv2 has, I just want to make sure that you are aware that the SoftHSM project now lives under the Commons Conservancy, and that governance decisions about the project are made by the SoftHSM Governance Board (on which we currently have a Red Hat representative, @letoams).

The force of habit made me to put the Red Hat copyright statement. I believe it wouldn't be a problem to remove it if it is against your current licensing policy. Let me know if I should remove the statement.

**Comment by rijswijk** [comment]
> > Thanks, and also thanks for the separate PR for this leak.
> > One final heads up: I see you added a Red Hat copyright statement in the test code for the feature. While that block is license-compatible with the 2-clause BSD license that SoftHSMv2 has, I just want to make sure that you are aware that the SoftHSM project now lives under the Commons Conservancy, and that governance decisions about the project are made by the SoftHSM Governance Board (on which we currently have a Red Hat representative, @letoams).
> 
> The force of habit made me to put the Red Hat copyright statement. I believe it wouldn't be a problem to remove it if it is against your current licensing policy. Let me know if I should remove the statement.

I don't believe it would be a problem, it's just to let you know that all code has been transferred to the SoftHSM project under the move to Commons Conservancy, and that if we merge this PR that will happen to this code as well.

**Comment by halderen** [comment]
Thanks for the other fix leaking memory, but after some additional digging I've found the memory leak in prepareSupportedMecahnisms(),  Its indeed related to some memory that otherwise wouldn't pose a problem, but with forking() becomes a bit more prominent.  I found it by just repeated forking, where the child forks and the parent just exits.  You see the heap slowly increasing.
Since this leak isn't really due to this fix, I'll just merge in this fix and create a seperate PR for it.

**Pull request merged**
