### PR TITLE
Add CKM_GENERIC_SECRET_KEY_GEN Support

### LINKED ISSUE #375: Support for CKM_GENERIC_SECRET_KEY_GEN
Currently using HMAC with PKCS11 2.4.0 is difficult as SoftHSM does not support generating generate secret generation via CKM_GENERIC_SECRET_KEY_GEN that many software packages require for using HMAC. Is there a planned addition for this in the near future?

Thanks.

### PR DESCRIPTION
**Pull request by daviddob**
Add support for CKM_GENERIC_SECRET_KEY_GEN which is required for HMAC operations in PKCS11 2.4.0.

Resolves #375

### CODE REVIEW

**Comment by gbolo** [comment]
nice, would love to have `CKM_GENERIC_SECRET_KEY_GEN` support in softhsm

**Comment by gbolo** [comment]
Just tested this, I can confirm that it works as expected. Good job

**Comment by bellgrim** [comment]
Thank you for this PR. Will check it out once I have finished some other issues in the backlog.

**Comment by npmccallum** [comment]
Any update on this? We (Red Hat) have started adding PKCS#11 support to  https://github.com/latchset/jose but we are running into this bug.

One comment about the implementation. I'm not sure it actually conforms to http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399398911 . My cursory glance over the code looks like it is supplying attributes besides `CKA_KEY_TYPE` and `CKA_CLASS`. https://github.com/opendnssec/SoftHSMv2/pull/376/commits/0393f7a97ef1a9c90cb735d05e383efff15600de#diff-ff3900333e6090272c9e40bb1fc2da27R6900

I don't think that is correct. Also, I don't see validation of the attributes `CKA_KEY_TYPE` and `CKA_CLASS` when specified in the template.

**Comment by bellgrim** [comment]
Made some changes so that we use the correct key type and also handle the KCV-attribute.

**Pull request merged**
